### ISSUE TITLE
Solve day 17 Challenge

### ISSUE THREAD

**Issue by debarghya472** [debarghya472/PythonChallenge#14]
Solve Day 17 Python challenge from WireUsChallenge

**Comment by Claw256** [comment]
I can solve this issue, can you assign this issue to me?

**Comment by debarghya472** [comment]
@Claw256 Day 17 challenge is over.  If you want You can solve and upload day 20 challenge. you are good to go.
<img width="248" alt="Screenshot 2020-10-07 at 10 26 47 AM" src="https://user-images.githubusercontent.com/54908977/95289133-a7937c80-0887-11eb-89f3-79d7a728c487.png">

First go through the contribution.md before contributing

DO create an new branch day_20 before creating PR
